### ISSUE TITLE
Thank you. :)  Team based config

### ISSUE THREAD

**Issue by fessyfoo** [Yelp/sensu_handlers#125]
I don't have another place to communicate with you guys.    I wanted to say thank you for your handler model and the team based configuration.    because of the team based configuration we're able to transition from hipchat to slack handler  by just updating a teams channel information rather than having to find every check defined for those teams and modify them all. 

thought you might like to know that that bit of forward looking design paid off for us in this transition. 

Thank you.

**Comment by somic** [comment]
cc @bobtfish @solarkennedy 

Thank you, we appreciate it.

I personally totally agree with you. I came to yelp when this team-focused model was already in place and I have continuously brought it up as one of the simplest but most impactful under-the-radar technical design decisions that we have.

**Comment by solarkennedy** [comment]
:heart:
