### ISSUE TITLE
Handlers are not CPU effecient

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/sensu_handlers#13]
Due to the the design, all handlers spawn for every event, each filters themselves, each queries the api for the same stashes, etc.

@bobtfish We talked about doing this as an extension. This sounds good, but it pretty scary.

Could we do some intermediate thing where the base handler is activated, does filtering, and then *it* decides what additional handlers to spawn depending on the event data? Pretty much just making 1 mega handler?

**Comment by somic** [comment]
Just found this issue here and thought I'd update it since it's been a while.

I am going to get sensu filters set up for pagerduty and jira handlers - currently blocked by having to upgrade to latest sensu-puppet (it includes my PRs that we need for this) which I am working on.

**Comment by solarkennedy** [comment]
Go for it! Filters seem like a great middle-ground between implementing everying "in process" with extensions and execing 4 processes upon every event.

**Comment by solarkennedy** [comment]
@somic You have done a ton of work on this. Closable?

**Comment by somic** [comment]
Yes, closing.
