### ISSUE TITLE
Develop autofixer handler

### ISSUE THREAD

**Issue by somic** [Yelp/sensu_handlers#34]
Autofixer could be a system that receives events from sensu and attempts to fix them if it's told how to do it. This handler will provide the plumbing necessary to make it happen.

Potential sequence of steps could be receive an event from sensu, determine if this event is actionable by autofixer at this point in time (for example, attempt to autofix only after N minutes of ongoing event), perform a specified action, mark event as "autofix has been applied" in case the autofix action fails to resolve the event (to provide means for escalation to higher intelligence entity like a human).

Or make "autofix has been applied" as a counter to support situations where we want to apply autofix up to N times and after that give up.

Let's build plumbing to teach the machines how to fix problems themselves!

**Comment by solarkennedy** [comment]
Some of this has been written here: https://github.com/sensu/sensu-community-plugins/blob/master/handlers/remediation/sensu.rb

**Comment by solarkennedy** [comment]
@somic is this close-able now that @pauloconnor's remediation integration?

**Comment by somic** [comment]
Yes, closing
