### ISSUE TITLE
pagerduty handler can sometimes emit too long of a description, and fail to page, which is bad

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/sensu_handlers#38]
We should truncate like we do in the irc handler. PD requires the description to be <= 1024 chars.

    errorsDescription is too long (maximum is 1024 characters)messageEvent object is invalidstatusinvalid event

The other wtf is that the error is not printed because of the *elegance* of our ruby.

Please also make the error reporting easier to discover by simply printing the output of the result if it didn't work:

```
    result = Redphone::Pagerduty.trigger_incident(
      :service_key  => api_key,
      :incident_key => incident_key,
      :description  => description,
      :details      => full_description_hash
    )
    puts result if  result['status'] != 'success'
    result['status'] == 'success'
```

**Comment by vulpine** [comment]
Fixed in e106709.
