### ISSUE TITLE
aws_prune should only consider "running" instances to be available

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/sensu_handlers#42]
We currently only consider "non terminated" instances when considering which ec2 instances to respect when activating handlers.

This causes alerts in the time between a server being terminated (in the `shutting-down` state) and when the server is *actually* `terminated`.

But I think we can do better by simply ignoring servers that are `shutting-down` *or* `terminated`, and then they will be pruned asap.

**Comment by solarkennedy** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html

**Comment by solarkennedy** [comment]
Pinging @somic @jglukasik or @loganrosen if they would like to do this, otherwise I'll take it.

**Comment by jaxxstorm** [comment]
Did anyone fancy this? If not, I'll take it..

**Comment by jaxxstorm** [comment]
Unless I'm vastly mistaken, I think we just need to add this to the hash reject:

```
|| s['state'] == 'terminated' || s['state'] == 'shutting-down'
```

Let me know @solarkennedy

**Comment by bobtfish** [comment]
shipit!

**Comment by solarkennedy** [comment]
Nice. ty!
