### ISSUE TITLE
Make aws-prune run "out of band" and not as a handler

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/sensu_handlers#43]
Running the aws-prune script as an even handler has two downsides:
* It is wasteful cpu-wise
* It means there is *always* a warning event while a server is being shut down

Running the aws-prune thing as a cron job could make this more efficient and prune terminated instances *faster*, without causing spurious alerts.

**Comment by solarkennedy** [comment]
Pinging @somic @jglukasik or @loganrosen if they would like to do this, otherwise I'll take it.

@georgebashi would like this to not use our cron::d wrapper or open source that dependency. (which we should!)

**Comment by jaxxstorm** [comment]
I can probably take this, but have a few questions before I go ahead. I'll follow up with you in person.

**Comment by solarkennedy** [comment]
Go for it. We are currently overloaded on our sensu/puppet servers and this would help a bit.

**Comment by solarkennedy** [comment]
This was done by aduko.
