### ISSUE TITLE
Remove `habitat` from pagerduty event ids in favor of `region` (I guess)

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/sensu_handlers#84]
We need to know what habitat the pagerduty events come from in order to do webhooks.
@bobtfish what are these webhooks anyway, Nagios stuff?

Till then we'll get duplicate pagerduty incidents for any kind of `source` based event. (server_side, sensu stuff, etc)

**Comment by bobtfish** [comment]
Both Nagios and Sensu - folks expect to be able to 'resolve' in PD and have
that reflected back.

Elastalert has unfortunately propagated this expectation significantly, as
it doesn't have any concept of 'resolve', so it expects humans to resolve
any alerts it generates

**Comment by solarkennedy** [comment]
Whoops, I had forgotten I already had #83 open.
