### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by dgoradia** [Yelp/sensu_handlers#85]
Thanks for the awesome work done here, especially the base handler. There are many parts of that I'd like to use in my own base handler along with much of my own functionality. 

In the spirit of sharing, I'd like to open source my work under the MIT license but you have no license specified so I'm not sure if I can. 

Can you clarify?

**Comment by solarkennedy** [comment]
Absolutely.

I already told legal (when I first open sourced this) that it would be Apache2, but I neglected to add a license file. I hope this works for you.

**Comment by dgoradia** [comment]
Wow, thanks guys for the amazingly fast response.
